add FirmwareUpdate.py
Mecademic/python_driver pull request #5
Opened 2020-08-25 19:44 UTC by onsimini

Add the firmware update file to the package.
I ll add a description in the readme file too.

2020-08-25 20:18 UTC, acoulombe commented on MecademicRobot/FirmwareUpdate.py
> +def main():
Do we want this feature to be a script that a customer can run or a class member function?

2020-08-25 20:20 UTC, acoulombe commented on MecademicRobot/FirmwareUpdate.py
> +def wait_for_robot_reboot(time_in_second):
Unused function

2020-08-26 11:30 UTC, alainbrassardMeca commented on MecademicRobot/FirmwareUpdate.py
> +    ''' Waiting dalay to let the robot finish updating.
dalay -> delay

2020-08-26 11:32 UTC, alainbrassardMeca commented on MecademicRobot/FirmwareUpdate.py
> +        time.sleep(1)
I would move the sleep somewhere else (probably before "requests.get") because it does not make much sense to get the update and wait 1 second before processing it. Would make more sense to wait 1 second, then get update and process it immediately.

2020-08-26 11:35 UTC, alainbrassardMeca commented on MecademicRobot/FirmwareUpdate.py
> +        time.sleep(1)
Oh... I see there is another sleep at the end of the loop. Why is there a sleep here too? Is it to wait for response of "requests.get"? There must be a better way to wait for the response. Using a sleep is not a good way (not reliable, and at the same time generally wasted time).

2020-08-26 11:37 UTC, alainbrassardMeca commented on MecademicRobot/FirmwareUpdate.py
> +    time.sleep(40)
Why sleep 40 here?
Should "wait_for_robot_reboot" be used here instead?
Printing a progress during that time would be wise. This is long, user will think the script is dead.

2020-08-26 12:43 UTC, acoulombe commented on MecademicRobot/FirmwareUpdate.py
> +        time.sleep(1)
I don't think it is required to have a sleep here. The version of the function I have only has the delay at the end of the loop and works well.

2020-08-26 12:48 UTC, acoulombe commented on MecademicRobot/FirmwareUpdate.py
> +                print(f'{new_progress}', end='')
You can add the argument flush=True to the print function so that the progress gets added to the output without needing a newline (progress will only display once the 100% is reached otherwise)

`print(f'{new_progress}', end='', flush=True)`

2020-08-26 13:29 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +def main():
I think they (support) prefer a script ...

2020-08-26 13:31 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +def wait_for_robot_reboot(time_in_second):
my bad, I ll push tha fix

2020-08-26 13:34 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +    ''' Waiting dalay to let the robot finish updating.
fix done

2020-08-26 19:19 UTC, jletendre-meca commented on MecademicRobot/FirmwareUpdate.py
> +    [robot_fw_path, robot_ip_address] = cli()
`cli()` -> `get_args()`

2020-08-26 19:24 UTC, jletendre-meca commented on MecademicRobot/FirmwareUpdate.py
> +        print(f'timeout ...')
Be more specific in the error print.  Something like "HTTP request timeout when posting Update request."
Also, trailing `...` are for when an action is in progress. Should not be used on error prints.
This also applies to requests.ConnectionError

2020-08-26 19:27 UTC, jletendre-meca commented on MecademicRobot/FirmwareUpdate.py
> +        r = requests.get(ip_address, 'update', timeout=10)
Exceptions are not properly handled here (see previous `requests.post`).

2020-08-26 19:28 UTC, jletendre-meca commented on MecademicRobot/FirmwareUpdate.py
> +        if r.text == '0':
This line requires a comment to explain it. Why would a returned text value of `'0'` trigger an immediate retry of the request?

2020-08-26 19:41 UTC, jletendre-meca commented on MecademicRobot/FirmwareUpdate.py
> +        status_code = int(request_answer.get('STATUS').get('Code'))
We should explicitly check for an absent `request_answer.get('STATUS')` to fail gracefully instead of aborting on an exception because `None.get('Code')` does not exist.

2020-08-28 18:01 UTC, sdahdah commented on MecademicRobot/FirmwareUpdate.py
> +            print(f'{request_answer.get("STATUS").get("MSG")}')
Use single quotes everywhere except docstrings and when you need a single quote inside your string

2020-08-31 13:38 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +                print(f'{new_progress}', end='')
done thanks

2020-08-31 13:40 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +    [robot_fw_path, robot_ip_address] = cli()
fix done

2020-08-31 13:43 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +        print(f'timeout ...')
fix done

2020-08-31 18:14 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +            print(f'{request_answer.get("STATUS").get("MSG")}')
fix done

2020-08-31 18:15 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +    print(f'Done. \nUpdate size is: ' + str(update_file_size) + 'B.')
fix done

2020-08-31 18:24 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +    update_file = open(file_path, 'rb')
fix done

2020-08-31 19:21 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +    ''' Send the update specified by file_path to the robot.
fix done

2020-08-31 19:22 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +    parser = argparse.ArgumentParser(description='Run the firmware Update of the robot.')
Thanks :D

2020-09-08 18:45 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +def main():
fix done

2020-09-08 18:45 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +        time.sleep(1)
fix done

2020-09-08 18:45 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +    time.sleep(40)
fix done

2020-09-08 18:46 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +        r = requests.get(ip_address, 'update', timeout=10)
fix done

2020-09-08 18:51 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +        if r.text == '0':
done

2020-09-08 18:51 UTC, onsimini commented on MecademicRobot/FirmwareUpdate.py
> +        status_code = int(request_answer.get('STATUS').get('Code'))
fix done

2020-09-09 19:29 UTC, meboutet approved these changes

2020-10-14 01:49 UTC, jletendre-meca requested changes

2020-10-14 01:49 UTC, jletendre-meca commented on MecademicRobot/FirmwareUpdate.py
> +            del(r)
I don't understand why you would need to delete `r` and `resp` here.

2020-10-14 01:49 UTC, jletendre-meca commented on MecademicRobot/RobotController.py
> +    def is_inerror(self):
```suggestion
    def is_in_error(self):
```

2020-10-14 01:49 UTC, jletendre-meca commented on MecademicRobot/RobotController.py
> +            Message from the robor.
```suggestion
            Message from the robot.
```

2020-10-14 01:49 UTC, jletendre-meca commented on MecademicRobot/RobotController.py
> +        error : booleen
```suggestion
        error : boolean
```

2020-10-14 01:49 UTC, jletendre-meca commented on MecademicRobot/RobotController.py
> +        status : booleen
```suggestion
        status : boolean
```

2020-10-14 01:49 UTC, jletendre-meca commented on MecademicRobot/RobotController.py
> +    def activatesim(self):
```suggestion
    def activate_sim(self):
```

2020-10-14 01:49 UTC, jletendre-meca commented on MecademicRobot/RobotController.py
> +    def deactivatesim(self):
```suggestion
    def deactivate_sim(self):
```

2020-10-14 01:49 UTC, jletendre-meca commented on MecademicRobot/RobotController.py
> +    def switch2etherCAT(self):
```suggestion
    def switch_to_ethercat(self):
```

2020-10-14 01:49 UTC, jletendre-meca commented on MecademicRobot/RobotController.py
> +    def gripperopen(self):
This function and all the following are all missing `_` (underscore) between the words.

2020-10-14 01:49 UTC, jletendre-meca commented on MecademicRobot/RobotController.py
> +    def gripperopen(self):
Unless with decide to make an exception and keep the same syntax as the TCP text API, but I don't think it's worth it.

2020-10-15 20:21 UTC, jletendre-meca approved these changes

2020-10-16 13:10 UTC, merged